# Run pytest with GitHub Actions
name: pytest

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install package
      run: |
        pip install .

    - name: Run pytest
      run: |
        pytest -v